### ISSUE TITLE
k-sigma Transform

### ISSUE THREAD

**Issue by HLIG** [megvii-research/PMRID#1]
Thanks for your great work! The k-sigma parameter in the code seems to be the same for whole CFA. Is it better to use 3 different parameters for R/G/B arrays?

**Comment by bigeagle** [comment]
You can try estimating channel-wise noise parameters.
According to my experience, different CFA channels have different noise-params, but the difference is small.

In practice, it is OK to set different params for RGB channel. However, `Gr` and `Gb` should use the same param, or the different denoising strength may cause green-imbalance (visible as maze artifact after demosaicking).

**Comment by HLIG** [comment]
OK, Thanks  a lot~
