### ISSUE TITLE
K-Sigma Estimation

### ISSUE THREAD

**Issue by zjysnow** [megvii-research/PMRID#10]
Hi, I have download the reno10x_noise dataset to estimate the k-sigma parameters, but I found that there are two folders have the same ISO=3938, is there anything wrong here?
Another question is that I found the E(x)-Var(x) curve is not always linear. When the luminance is higher, the curve is more non-linear, I want to known if I miss some pre-processing. Now I just read the raw data and minus the black level. Also I tried to use different strategy to sample the data and cannot achieve the result of yours, is there any trick here?

**Comment by zjysnow** [comment]
sorry, I found that the last image in group iso=3200 is iso=3938, I use the last data as x, so I got the wrong data

**Comment by zjysnow** [comment]
重现了，谢谢

**Comment by nnzs9248** [comment]
> 重现了，谢谢

NB

**Comment by hellohellosun01** [comment]
> Hi, I have download the reno10x_noise dataset to estimate the k-sigma parameters, but I found that there are two folders have the same ISO=3938, is there anything wrong here?

如何解决的？

**Comment by zjysnow** [comment]
> > Hi, I have download the reno10x_noise dataset to estimate the k-sigma parameters, but I found that there are two folders have the same ISO=3938, is there anything wrong here?
> 
> 如何解决的？

这个事因为最后一张图分错了，至少那个分类的最后一张图的info是错的

**Comment by shigebendana** [comment]
> 你好，我下载了 reno10x_noise 数据集来估计 k-sigma 参数，但我发现有两个文件夹具有相同的 ISO=3938，这有什么问题吗？ 另一个问题是，我发现 E(x)-Var(x) 曲线并不总是线性的。当亮度较高时，曲线更加非线性，我想知道我是否错过了一些预处理。现在我只读取原始数据并减去黑色级别。我还尝试使用不同的策略对数据进行采样，但无法达到你的结果，这有什么技巧吗？

请问一下，您是把所有的像素都算E(X)嘛？还是有别的采样策略 我复现出来的数值是：ISO vs k (with outliers): k = 0.000603 * ISO + 0.006624 ISO vs sigma_r_squared (with outliers): sigma_r_squared = -0.225462 * ISO^2 + 0.000739 * ISO + 0.000001，需不需要取掉异常点呢？

**Comment by cxy2333-hue** [comment]
> > 你好，我下载了 reno10x_noise 数据集来估计 k-sigma 参数，但我发现有两个文件夹具有相同的 ISO=3938，这有什么问题吗？ 另一个问题是，我发现 E(x)-Var(x) 曲线并不总是线性的。当亮度较高时，曲线更加非线性，我想知道我是否错过了一些预处理。现在我只读取原始数据并减去黑色级别。我还尝试使用不同的策略对数据进行采样，但无法达到你的结果，这有什么技巧吗？
> 
> 请问一下，您是把所有的像素都算E(X)嘛？还是有别的采样策略 我复现出来的数值是：ISO vs k (with outliers): k = 0.000603 * ISO + 0.006624 ISO vs sigma_r_squared (with outliers): sigma_r_squared = -0.225462 * ISO^2 + 0.000739 * ISO + 0.000001，需不需要取掉异常点呢？

请问你解决了吗，解决方法是什么？

**Comment by cxy2333-hue** [comment]
> > 你好，我下载了 reno10x_noise 数据集来估计 k-sigma 参数，但我发现有两个文件夹具有相同的 ISO=3938，这有什么问题吗？ 另一个问题是，我发现 E(x)-Var(x) 曲线并不总是线性的。当亮度较高时，曲线更加非线性，我想知道我是否错过了一些预处理。现在我只读取原始数据并减去黑色级别。我还尝试使用不同的策略对数据进行采样，但无法达到你的结果，这有什么技巧吗？
> 
> 请问一下，您是把所有的像素都算E(X)嘛？还是有别的采样策略 我复现出来的数值是：ISO vs k (with outliers): k = 0.000603 * ISO + 0.006624 ISO vs sigma_r_squared (with outliers): sigma_r_squared = -0.225462 * ISO^2 + 0.000739 * ISO + 0.000001，需不需要取掉异常点呢？

我的sigma²拟合出来都很异常

ISO 112: k = 0.084247, sigma² = 0.000000
ISO 200: k = 0.006305, sigma² = 0.006296
ISO 400: k = 0.080112, sigma² = 0.000000
ISO 800: k = 0.080975, sigma² = 0.000000
ISO 1191: k = 0.090401, sigma² = 0.000000
ISO 1600: k = 0.079910, sigma² = 0.000000
ISO 2381: k = 0.088905, sigma² = 0.000000
ISO 3200: k = 0.079626, sigma² = 0.000000
ISO 3938: k = 0.078324, sigma² = 0.000000
ISO 4655: k = 0.068352, sigma² = 0.000000
ISO 5389: k = 0.077788, sigma² = 0.000000
ISO 6400: k = 0.078038, sigma² = 0.000000

=== 全局拟合结果 ===
k(ISO) = 0.000002 * ISO + 0.069401
sigma²(ISO) = 0.000000 * ISO² + -0.000001 * ISO + 0.001908

**Comment by cxy2333-hue** [comment]
> 重现了，谢谢

您好，请问您的分箱是怎么分的？同时想了解一下是否需要做采样？试了多种方式没有得到代码中的系数
