### ISSUE TITLE
Error when running evaluation code 

### ISSUE THREAD

**Issue by amandayeyan** [megvii-research/PMRID#12]
Hello, 
Thanks for your great work done. When I run the run_benchmark.py, I encountered the following error. Can you help?  I am using python=3.6. 

![image](https://user-images.githubusercontent.com/18046926/169493097-37b7ed25-1d76-4cdd-810b-95ee8a616289.png)

**Comment by amandayeyan** [comment]
> Hello, Thanks for your great work done. When I run the run_benchmark.py, I encountered the following error. Can you help? I am using python=3.6.
> 
> ![image](https://user-images.githubusercontent.com/18046926/169493097-37b7ed25-1d76-4cdd-810b-95ee8a616289.png)

I figured out myself. Just add one line after ln71 in run_benchmark.py : inp = mge.tensor(inp)
Hope it would help someone with the same errors encountered.

**Comment by liujianwei0225** [comment]
Thanks a lot! I just met the same problem, thanks for your solution! :)
