### ISSUE TITLE
cannot open torch_pretrained.ckp  and json.load(f) error

### ISSUE THREAD

**Issue by kaka36** [megvii-research/PMRID#2]
states = pickle.load(f) error

UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

for x in json.load(f)
TypeError: object() takes no parameters

**Comment by bigeagle** [comment]
how do you run the script?
which python version?

**Comment by bigeagle** [comment]
Hi, the evaluation script is only for mge pretrained model. The torch evaluation script is not provided yet.

**Comment by ireneMsm2020** [comment]
how to load torch_pretrained.ckp? when I try to run torch.load(' torch_pretrained.ckp'), i get an error .

RuntimeError: models/torch_pretrained.ckp is a zip archive

**Comment by zhangyunming** [comment]
> how to load torch_pretrained.ckp? when I try to run torch.load(' torch_pretrained.ckp'), i get an error .
> 
> RuntimeError: models/torch_pretrained.ckp is a zip archive

have you test in pytorch?
