### ISSUE TITLE
what's the purpose of this code ?

### ISSUE THREAD

**Issue by lettifay** [megvii-research/PMRID#7]
https://github.com/megvii-research/PMRID/blob/8ebb9e8e96559881dee957f34243933c5beb77dd/run_benchmark.py#L106

**Comment by bigeagle** [comment]
This is [bayer-pattern unification](https://arxiv.org/abs/1904.12945).

**Comment by lettifay** [comment]
> This is [bayer-pattern unification](https://arxiv.org/abs/1904.12945).

thanks a lot.
